# Generated by Django 4.0.2 on 2022-02-15 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_receita', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('tempo_preparo', models.IntegerField()),
                ('rendimento', models.TextField(max_length=100)),
                ('categoria', models.TextField(max_length=100)),
                ('data_receita', models.DateField(blank=True, verbose_name=datetime.datetime(2022, 2, 14, 22, 2, 13, 737606))),
            ],
        ),
    ]
