# Generated by Django 4.0.2 on 2022-02-15 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateField(blank=True, verbose_name=datetime.datetime(2022, 2, 14, 22, 2, 50, 887838)),
        ),
    ]
