# Generated by Django 4.0.2 on 2022-02-15 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasapp', '0002_alter_receita_data_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateField(blank=True, verbose_name=datetime.datetime(2022, 2, 15, 20, 43, 38, 959720)),
        ),
    ]
