# Generated by Django 4.0.2 on 2022-02-16 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitasapp', '0006_receita_foto_receita_alter_receita_data_receita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='data_receita',
            field=models.DateField(blank=True, verbose_name=datetime.datetime(2022, 2, 15, 21, 53, 40, 945634)),
        ),
    ]
